version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Set the root password here
      MYSQL_DATABASE: users_app           # Optional: Create a database on startup
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   # Allow empty password for root (not recommended for production)
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

volumes:
  db_data:
